### ISSUE TITLE
Client Authentication issue

### ISSUE THREAD

**Issue by pearlmansara** [ChiChou/bagbak#127]
Before you submit the issue, please check the FAQ section in Wiki: https://github.com/ChiChou/bagbak/wiki#faq
Then delete this section.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - nodejs: [e.g. v18.16.0]
 - frida on device version
 - iOS and jailbreak version
 - The app you are trying to work on [e.g. com.example.app, better with AppStore link]

**Additional context**

**Comment by pearlmansara** [comment]
[info] pulling app bundle from device, please be patient
/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/client.js:865
        const err = new Error('All configured authentication methods failed');
                    ^

Error: All configured authentication methods failed
    at doNextAuth (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/client.js:865:21)
    at tryNextAuth (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/client.js:1082:7)
    at USERAUTH_FAILURE (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/client.js:430:11)
    at 51 (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/handlers.misc.js:408:16)
    at Protocol.onPayload (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/Protocol.js:2052:10)
    at AESGCMDecipherBinding.decrypt (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/crypto.js:1086:26)
    at Protocol.parsePacket [as _parse] (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
    at Protocol.parse (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
    at IOStream.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/ssh2/lib/client.js:775:21)
    at IOStream.emit (node:events:513:28) {
  level: 'client-authentication'
}

Node.js v18.13.0

I have changed the environment variable to be the SSH credentials to the jailbroken device and validated that the creds work but its not working with this tool. Am I doing something wrong?

**Comment by ChiChou** [comment]
Yes, if you use custom password you need to specify `SSH_USERNAME` at the same time
