### ISSUE TITLE
ver3.2.1 still do not contain keybagd.js

### ISSUE THREAD

**Issue by ytoku** [ChiChou/bagbak#132]
**Describe the bug**
bagbak 3.2.1 does not contain keybagd.js.
`package.json` still refer `/agent/installer.js`.

```
  "files": [
    "index.js",
    "/agent/inject.js",
    "/agent/installer.js",
    "/agent/launchd.js",
    "/bin",
    "/lib/"
  ],
```

**To Reproduce**
- Execute `npx bagbak (name)`

**Expected behavior**
No errors

**Screenshots**
```
$ npx bagbak (name)
node:internal/fs/promises:633
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open '/home/user/.npm/_npx/b10d280f322d7514/node_modules/bagbak/agent/keybagd.js'
    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async BagBak.dump (file:///home/user/.npm/_npx/b10d280f322d7514/node_modules/bagbak/index.js:114:7)
    at async BagBak.pack (file:///home/user/.npm/_npx/b10d280f322d7514/node_modules/bagbak/index.js:257:5)
    at async main (file:///home/user/.npm/_npx/b10d280f322d7514/node_modules/bagbak/bin/bagbak.js:144:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/.npm/_npx/b10d280f322d7514/node_modules/bagbak/agent/keybagd.js'
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - nodejs: v21.4.0
 - frida on device version: 16.1.10
 - iOS and jailbreak version: iOS 16.6 / palera1n v2.0.0-beta.8
 - The app you are trying to work on: Any

**Additional context**

**Comment by ChiChou** [comment]
Thanks for reporting!
