### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by jialeguan** [ChiChou/bagbak#144]
Before you submit the issue, please check the FAQ section in Wiki: https://github.com/ChiChou/bagbak/wiki#faq
Then delete this section.

**Describe the bug**
As the title

**To Reproduce**
Command: bagbak -o ./de_apps com.vividseats.VividSeatsMobile

**Expected behavior**
Output:
[info] pulling app bundle from device, please be patient
[info] downloaded 1048 files and 408 folders
[info] app bundle downloaded
node:internal/fs/promises:637
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: EACCES: permission denied, open '/var/folders/0x/pj5qcj0s7kl7cfrz1rpv7yh40000gn/T/bagbak/com.vividseats.VividSeatsMobile/Payload/VividSeats.app/VividSeats'
    at async open (node:internal/fs/promises:637:25)
    at async parse (file:///opt/homebrew/lib/node_modules/bagbak/lib/macho.js:62:14)
    at async #visitFile (file:///opt/homebrew/lib/node_modules/bagbak/lib/scan.js:93:20)
    at async AppBundleVisitor.visitRoot (file:///opt/homebrew/lib/node_modules/bagbak/lib/scan.js:75:9)
    at async AppBundleVisitor.encryptedBinaries (file:///opt/homebrew/lib/node_modules/bagbak/lib/scan.js:131:40)
    at async BagBak.dump (file:///opt/homebrew/lib/node_modules/bagbak/index.js:134:17)
    at async BagBak.pack (file:///opt/homebrew/lib/node_modules/bagbak/index.js:254:5)
    at async main (file:///opt/homebrew/lib/node_modules/bagbak/bin/bagbak.js:144:7) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/var/folders/0x/pj5qcj0s7kl7cfrz1rpv7yh40000gn/T/bagbak/com.vividseats.VividSeatsMobile/Payload/VividSeats.app/VividSeats'
}

Node.js v21.7.1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 14.4 (23E214)
 - nodejs: v. 21.7.1
 - frida on device version iOS 16.3.1. palera1n
 - iOS and jailbreak version iPhone X
 - The app you are trying to work on [e.g. com.example.app, better with AppStore link]
com.vividseats.VividSeatsMobile

**Comment by jialeguan** [comment]
之前说3.3这个问题被解决了，这个app还是有这样的问题，希望能看看这个问题～

**Comment by ChiChou** [comment]
> 之前说3.3这个问题被解决了，这个app还是有这样的问题，希望能看看这个问题～

旧版 bug 会影响 iOS 端的文件属性，需要卸掉应用重装…造成不便深表歉意

**Comment by jialeguan** [comment]
明白了🫡 多谢回复～
