### ISSUE TITLE
ReferenceError: Action is not defined at Function.connect

### ISSUE THREAD

**Issue by esoteric-programmer** [ChiChou/bagbak#41]
I cannot connect to the device.

I have started frida-server as root user at the device:
`$ frida-server -l 0.0.0.0:4444`

When I run bagbak, I get:
```
$bagbak -H 192.168.1.64:4444 -l
FATAL ERROR
ReferenceError: Action is not defined
    at Function.connect (/home/[[....]]/.nvm/versions/node/v13.2.0/lib/node_modules/bagbak/lib/device.js:15:17)
    at main (/home/[[....]]/.nvm/versions/node/v13.2.0/lib/node_modules/bagbak/go.js:380:27)
    at Object.<anonymous> (/home/[[....]]/.nvm/versions/node/v13.2.0/lib/node_modules/bagbak/go.js:430:1)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by esoteric-programmer** [comment]
I can connect using USB. It's a problem with WiFi connection.

**Comment by ChiChou** [comment]
Sorry, there's a typo

Will test the patch and publish a new version

**Comment by esoteric-programmer** [comment]
Very quick reaction, wow! Now it's working, thank you very much.
Btw., this is a great tool, very handy. I like it. Thank you for creating this. :-)
