### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by paradiseduo** [ChiChou/bagbak#48]
npm version:
```
➜  ~ node --version
v14.5.0
➜  ~ npm --version
6.14.5
```

```
➜  ~ bagbak
/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/out/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/out/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/default/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/compiled/14.5.0/darwin/x64/frida_binding.node
 → /Users/xmly/frida_binding.node
    at bindings (/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/native.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/cancellable.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1201:30) {
  tries: [
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/out/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/out/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/default/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/compiled/14.5.0/darwin/x64/frida_binding.node',
    '/Users/xmly/frida_binding.node'
  ]
}
```

**Comment by blakkbird9** [comment]
In the same situation: 
node --version    v14.6.0
npm --version    6.14.6
OS: Ubuntu 20.04


$ bagbak -l
/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/out/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/out/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/default/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/compiled/14.6.0/linux/x64/frida_binding.node
 → /home/dario/Downloads/node-v12.18.3-linux-x64/bin/frida_binding.node
    at bindings (/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/native.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/cancellable.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1236:30) {
  tries: [
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/out/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/out/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/default/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/compiled/14.6.0/linux/x64/frida_binding.node',
    '/home/dario/Downloads/node-v12.18.3-linux-x64/bin/frida_binding.node'
  ]
}

**Comment by ChiChou** [comment]
Use node.js 12.x (Long Term Support)

**Comment by blodoli** [comment]
I'm facing the same issue. Here's the output
OS: Parrot

```
$ node --version
v12.18.4
$ npm --version
6.14.6
$ bagbak -l
/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/out/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/Debug/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/out/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/Release/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/build/default/frida_binding.node
 → /usr/local/lib/node_modules/bagbak/node_modules/frida/compiled/12.18.4/linux/x64/frida_binding.node
 → /home/bianca/frida_binding.node
    at bindings (/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/native.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/cancellable.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  tries: [
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/out/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/Debug/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/out/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/Release/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/default/frida_binding.node',
    '/usr/local/lib/node_modules/bagbak/node_modules/frida/compiled/12.18.4/linux/x64/frida_binding.node',
    '/home/bianca/frida_binding.node'
  ]
}
```

I also tried on a Mac and I couldn't even install it, but I think the problem might be frida. Here's the output:

```
$ sudo npm install -g bagbak
/Users/bianca/.nvm/versions/node/v12.18.4/bin/bagbak -> /Users/bianca/.nvm/versions/node/v12.18.4/lib/node_modules/bagbak/go.js

> frida@12.11.17 install /Users/bianca/.nvm/versions/node/v12.18.4/lib/node_modules/bagbak/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.18.4 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /Users/bianca/.nvm/versions/node/v12.18.4/lib/node_modules/bagbak/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/bianca/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/bianca/.nvm/versions/node/v12.18.4/bin/node" "/Users/bianca/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bianca/.nvm/versions/node/v12.18.4/lib/node_modules/bagbak/node_modules/frida
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.11.17 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@12.11.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bianca/.npm/_logs/2020-09-23T13_34_52_889Z-debug.log
```

**Comment by ChiChou** [comment]
According to this release, it does not provide prebuild for node 12 LTS (abi 72):
https://github.com/frida/frida/releases/tag/12.11.17

But the latest release now (14.12.0) is supported
https://nodejs.org/en/download/current/

So please install 14.12.0 instead.

References
[1]. [nodejs releases and abi](https://nodejs.org/en/download/releases/)

**Comment by blodoli** [comment]
Great. It works with 14.12.0. Thanks!

**Comment by AkshayJainG** [comment]
node version 
`v14.15.0`
npm version 
`6.14.8`


```
bagbak
/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/native.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Comment by ChiChou** [comment]
@AkshayJainG try `npm uninstall -g frida` and `npm install -g bagbak`

**Comment by AkshayJainG** [comment]
```
/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/usr/local/lib/node_modules/bagbak/node_modules/frida/build/Release/frida_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/usr/local/lib/node_modules/bagbak/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/native.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Still same :(

**Comment by gelosecurity** [comment]
I figured out the issue. 

Turns out the installation package **only works for node v14.x, not with 15.x.**

Try installing v14.x here: https://nodejs.org/en/download/ 

![bagbak](https://user-images.githubusercontent.com/49821326/111231244-29f63a00-85a6-11eb-9619-f5ca088e8d4c.png)

**Comment by ChiChou** [comment]
For anyone that could possibly run into the same issue
[How do I decide which version of nodejs to use?](https://github.com/ChiChou/Grapefruit/wiki/How-do-I-decide-which-version-of-nodejs-to-use%3F)
