### ISSUE TITLE
Doesnt work with new frida 16

### ISSUE THREAD

**Issue by Gorge123** [ChiChou/bagbak#82]
You marked previous report as complete but it not works.
npm install -g bagbak downloades frida 15.2.2 version.
When frida 16.0.1 installed manually and codesigned it also not works:
TypeError: Bad argument, expected a string
    at Session.createScript (/usr/local/lib/node_modules/bagbak/node_modules/frida/dist/session.js:37:52)
    at dump (/usr/local/lib/node_modules/bagbak/go.js:279:32)
    at async main (/usr/local/lib/node_modules/bagbak/go.js:406:5)

seems some frida api changed.

**Comment by ChiChou** [comment]
The publish action failed. Please upgrade to the latest `npm i -g bagbak@latest` (2.4.0 at the moment)
